name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create module.zip
        run: zip -r ./module.zip module.json LICENSE styles/ scripts/ templates/ languages/

      - name: Upload module.zip to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.event.release.tag_name }}
          artifacts: "./module.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
