name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create module.zip
        run: zip -r ./module.zip module.json LICENSE styles/ scripts/ templates/ languages/

      - name: Upload assets to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./module.zip --clobber
          gh release upload ${{ github.event.release.tag_name }} ./module.json --clobber
